AppBundle\Entity\Comments:
    type: entity
    table: comments
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        type:
            type: integer
            nullable: false
        entityId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: entity_id
        author:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        content:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: created_at
    lifecycleCallbacks: {  }
