AppBundle\Entity\Stats:
    type: entity
    table: stats
    repositoryClass: AppBundle\Repository\StatsRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        ip:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
        browse:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: created_at
    lifecycleCallbacks: {  }
